apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-container
  template:
    metadata:
      labels:
        app: python-container
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: python-container
        image: 703862985210.dkr.ecr.us-east-1.amazonaws.com/main-repository/depi-api:latest
